### ISSUE TITLE
Collecting & Storing Information

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#1]
We should probably collect more feedback data. Some ideas:
- [x] User ID (if user is logged in)
- [x] Name/Email (optional, see #7)
- -IP address- (not needed)
- [x] Browser (detect from user agent)

How easy would it be to implement this in the feedback.js script?

Open question: How should this data be stored in the database?

**Comment by swissspidy** [comment]
Note: If the user submitting the post is already logged in, WordPress automatically sets it as the post author. It's just a matter of displaying it in the backend (see #4 for that)

**Comment by neverything** [comment]
@swissspidy I would love a setting in the Plugin that allows either loggedin users only or all users to send feedback, what do you think?

**Comment by swissspidy** [comment]
@neverything It's currently only possible via a filter, but I agree with you. Probably means refactoring the plugin a bit (two different class files). What do you think?

**Comment by neverything** [comment]
@swissspidy wouldn't a filter be enough? What benefits do you see in splitting it into two classes and would it be possible without repeating yourself in the code?

Basically the filter solution would be fine in my opinion.

**Comment by swissspidy** [comment]
@neverything The filter is available [here](https://github.com/wearerequired/user-feedback/blob/master/user-feedback.php#L265).
Splitting it up would be easier to maintain, because adding settings page needs a couple of lines of code. However, if we only use the filter, this shouldn't be needed.

**Comment by swissspidy** [comment]
The following information is currently being sent by the script:
- Browser Info
  - Name and version, e.g. "Chrome 40" (should this be separated?)
  - `navigator.cookieEnabled`
  - `navigator.platform`
  - `navigator.userAgent`
- Current URL
- Theme
  - Theme name
  - Stylesheet (slug)
  - Current template (e.g. `index.php`)
- Language
- User (optional, only for guests)
  - Name
  - Email address

WordPress detects the currently logged in user in the backend automatically.

Data that'd make sense as single meta key (used often, needed for sorting, stats, etc.):
- Browser name
- Platform
- Language
- URL / current post (can be guessed using `url_to_postid()`)

Any others?

Note: User is difficult, because only guests would be added as post meta. Otherwise the regular `post_author` field in the `wp_posts` table can be used.

**Comment by derpaschi** [comment]
For logged in users, we should also store the name und email address into the feedback record to take a current snapshot (email could change, name could change, and we're able to sort and filter in easier way).

All other infos looks good to me.

**Comment by swissspidy** [comment]
@hubeRsen But the logged in user who submitted the feedback will always be the same. Agree that filtering & sorting is easier though. Or maybe some SQL magic is needed then :)

**Comment by neverything** [comment]
So far I can't come up with additional fields that need to be stored. I personally don't think we need to split the browser name and version.

**Comment by swissspidy** [comment]
@neverything @hubeRsen See my first pass at this in 9cfd713ded619eabf64a13971bcc883c2dbca78b

**Comment by neverything** [comment]
Nice! Didn't come across `array_map()` in a while, good reminder for myself :memo:
