### ISSUE TITLE
Trigger Custom JavaScript Events

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#10]
For analytics it could be nice to track if the feedback module was launched, closed, etc.

In jQuery it could look something like this:

```
$.event.trigger({
  type: "user_feedback_close",
  message: msg,
  time: new Date()
});
```

Possible events
- Feedback module started (click on the button in the bottom right corner)
- Feedback closed
- Next/Back buttons clicked
- Screenshot is taken
- Highlighted something
- Submission successful
- Submission failed 

See [jQuery docs](https://learn.jquery.com/events/introduction-to-custom-events/)

**Comment by neverything** [comment]
I guess this would be useful, depending on the amount of work it would take, we can add this to the backlog maybe?

**Comment by swissspidy** [comment]
@neverything Providing the events (hooks) is easy (see snippet above). But I agree that actually _using_ them is something for the backlog.

**Comment by swissspidy** [comment]
For the backlog:

There could be a nice analytics dashboard for the plugin, or we could just use Google Analytics. Both could be nice extensions for the main plugin.

**Comment by swissspidy** [comment]
Reconsider this with the new Backbone base.

**Comment by swissspidy** [comment]
See also https://core.trac.wordpress.org/ticket/21170
