### ISSUE TITLE
SLA Client Personas

### ISSUE THREAD

**Issue by KarinChristen** [wearerequired/user-feedback#11]
Da wir ja noch weitere Plugins für unsere Kunden planen, finde ich es wichtig, dass wir wissen für wen wir designen. Deshalb werde ich versuchen Personas zu identifizieren, welche wir immer wieder hervor holen können, wenn wir was für unsere SLA Clients bauen. 

Auch damit der Silvan dann was zu erzählen hat am WCEU, habe ich mal ein Dokument angefangen: 
https://docs.google.com/document/d/10qqlWMVhjGWCIwfONPBnWYp8lBn8Ol7dYqxD68aFC0k/edit?usp=sharing

@neverything @swissspidy @hubeRsen es wäre schön wenn ihr mir beim Sammeln der Infos helfen könntet.

**Comment by KarinChristen** [comment]
Jetzt wo ich durch all die Support Mails gehe, wäre es vielleicht auch noch nützlich wenn das Feedback Plugin auch gleich für Change Requests da sein könnte, was denkt ihr?

**Comment by neverything** [comment]
@KarinChristen sicherlich auch eine Möglichkeit für kleine Änderungen, aber grössere Changes werden ja sowieso jeweils geplant.

**Comment by swissspidy** [comment]
@KarinChristen Can this ticket be closed?
