### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#12]
Most of the layouts are quite static. We should make the CSS more responsive. Also, what about touch support? No idea if touch works.

**Comment by swissspidy** [comment]
Probably not something for v1, as we focus on desktop for now.

**Comment by neverything** [comment]
We could try to have basic support for touch, but it would need a different
interface... @karinchristen ideas?

**Comment by swissspidy** [comment]
Currently there are three main problems on mobile:
- The bottom bar is too big. There's just not enough space for something like that.
- The modals are too wide. Maybe they should be be rectangular like the phone screen?
- We don't track `touchstart` / `touchend` events, so highlighting doesn't work (screenshot works though!).

What I imagine is that when you click on the "Feedback" button, it turns into a circle you drag around. Once you drop it, you can leave a message and your name. Done.

**Comment by neverything** [comment]
+1 for the approach that on mobile the circle is draggable so users can
select an area and comment on it directly.

**Comment by swissspidy** [comment]
Closing for now.
