### ISSUE TITLE
Browserify Support

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#15]
The JavaScript file is about ~700 lines long. We could split everything up and put each view in its own file using [Browserify](http://browserify.org/). This would be part of our Grunt config.

Some other projects already using it successfully: WordPress, Shortcake

**Comment by neverything** [comment]
I haven't tried Browserify yet, but if the code is cleaner and easier to maintain, I'm all in for it.

**Comment by swissspidy** [comment]
@neverything Have a look at the [feature/browserify](https://github.com/wearerequired/user-feedback/tree/feature/browserify) branch to see how I've done it. Not sure if it's the right way, but it works.

See 7a7a408cdbdd920e7bd763c2b8e6a01df5afec4d for pros/cons.

Any suggestions? Is it really cleaner now?

I'll happily merge it into the `develop` branch when it looks good to you.

**Comment by neverything** [comment]
@swissspidy not sure wether it's actually better this way. 10kb more is a bit heavy, but if it's easier to maintain, I'm willing to do it this way.

On the feature/browserify branch the highlight feature doesn't save the highlighted area at the moment.

**Comment by swissspidy** [comment]
I think I have to put that into relation. Browserify itself is pretty lightweight according to the docs. The main difference comes from adding the templates (~6kb) to the JS. And I think they shouldn't belong to the php file.

Maybe we could consolidate some views into single files, but I think it's more consequent like this.

Highlighting works for me: https://cloudup.com/cyIpiPDIr_H. Where's the problem exactly?

**Comment by swissspidy** [comment]
Just shaved another 1kb from the minified js, see b8fecc8d05c602497a611f284a0eb249d7acad98

**Comment by swissspidy** [comment]
If we consider minifyify, we could make the files even smaller. There are almost no docs yet on how to use it with grunt..

**Comment by neverything** [comment]
Saving data: Nice!

Here is a video of the bug I'm having: https://www.dropbox.com/s/pfj7ss58rr0v5vn/user-feedback.mov?dl=0 maybe I have to use grunt locally to make it work?

**Comment by swissspidy** [comment]
@neverything ah thanks! somehow it didn't trigger that error on my instance, but I fixed it nonetheless.

Can you check out the latest version and test it again?

**Comment by neverything** [comment]
@swissspidy works perfectly now! :+1:

**Comment by swissspidy** [comment]
🎉🎉

Let's settle this for now. Maybe I get some additional feedback on twitter or we could talk about it in London. Will merge it afterwards.

**Comment by swissspidy** [comment]
Additional note to the `remapify` feature: Version 1.4.4 didn't work, so I stuck with 1.4.3.

**Comment by swissspidy** [comment]
Until I find a solution to 6188c9b54c3189f29159d3778dcf4f9620e28448, this will do it for the moment.

**Comment by swissspidy** [comment]
3f5bec2de4615142e43355d5105a56fa29580f00 successfully merged `feature/browserify` into the `develop` branch.
