### ISSUE TITLE
font-color im Feedback Module setzen

### ISSUE THREAD

**Issue by KarinChristen** [wearerequired/user-feedback#2]
Im Moment nimmt es die font-color geerbt vom <p>. Wenn aber die Schrift der Website weiss ist wie im Screenshot zu sehen ist, dann sieht man keinen Text. Am besten wir überschreiben dies jeweils mit #feedback-module p {color:#000} oder so, damit wir sicherstellen können dass die Schrift immer sichtbar ist.
![screenshot 2015-02-13 21 48 12](https://cloud.githubusercontent.com/assets/145720/6186793/7e66d8ee-b3d2-11e4-8179-56f79f63dc1a.png)

**Comment by swissspidy** [comment]
Hoppla :)

Das CSS kommt direkt vom verwendeten Feedback.js Script, habe es noch nicht wirklich angeschaut. Werde ich sicher anpassen.

Dachte, hier könnte man eh auf Sass setzen, um ein paar Dinge zu vereinfachen (Minify, bessere Icons, etc.) und zu verschönern.
