### ISSUE TITLE
Improve Wording

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#21]
- [ ] Wording in the wizard
- [ ] Make the final wording for the email (currently lacking a nice text + lots of information)

**Comment by neverything** [comment]
@KarinChristen I'll start come up with something regarding the wording, but since it's an important part of the UI I would love your help/feedback on it, ok?

**Comment by neverything** [comment]
@swissspidy on what branch would you like me to improve the wording?

**Comment by swissspidy** [comment]
@neverything For this task you can probably just work on the `develop` branch. For bigger things I create a new feature branch off `develop` (git-flow like). Looking forward to your first commit :smiley:

**Comment by neverything** [comment]
@swissspidy thanks and thanks for using git-flow style, I like it.

**Comment by swissspidy** [comment]
Note: There's now also a copy sent to the user (see #26), which probably needs some fine-tuning as well.
