### ISSUE TITLE
Feedback Senden - E-Mail an User

### ISSUE THREAD

**Issue by KarinChristen** [wearerequired/user-feedback#26]
Als ich das Plugin der Marie-Christine gezeigt habe, hatte sie den Input, dass es von Nutzen sein könnte, dass man eine Checkbox hätte "Sende eine Kopie dieser E-Mail an mich (Empfänger ist die E-Mail Adresse des Accounts)"

Ich fand diesen Wunsch noch pausibel. @swissspidy kannst du das beim Senden Button noch irgendwo einbauen?

**Comment by swissspidy** [comment]
Automatische Kopie ist kein Thema? Dann braucht es nicht noch eine Checkbox :)

Kann ich auf jeden Fall anschauen. Braucht dann sicher einen anderen Text für die Kopie, d.h. Translations.

**Comment by swissspidy** [comment]
Email to the blog admin:
![bildschirmfoto 2015-04-21 um 09 21 07](https://cloud.githubusercontent.com/assets/841956/7247250/d2643a86-e807-11e4-8033-ae3d4b004546.png)

Email to the user:
![bildschirmfoto 2015-04-21 um 09 20 55](https://cloud.githubusercontent.com/assets/841956/7247251/d26595f2-e807-11e4-9906-3a08b942ca86.png)
