### ISSUE TITLE
Drag&Drop Behaviour des Feedback Module 

### ISSUE THREAD

**Issue by KarinChristen** [wearerequired/user-feedback#3]
Im Moment ist sehr störend, dass wenn man in das Feedback Module klickt, dass dann dieses an der Maus klebt bis man wieder klickt. Die Affordance ist nicht ersichtlich. Ich denke es wäre benutzerfreundlicher wenn wir eine Header-Bar machen mit einem Drag-Icon. Bei Klick auf die Bar (mouse down) kann man dieses platzieren. (Normales Drag&Drop-Verhalten). 

Aber ich denke, dass ist einfach noch nicht fertig.

**Comment by swissspidy** [comment]
@KarinChristen Bei mir (Firefox & Chrome) lässt sich das Fenster nur bewegen, wenn ich wirklich auf der Maus bleibe, also in meinen Augen normales Drag & Drop Verhalten.

Wie wäre es mit Drag-Icon bei Mouseover, damit man das als User auch schnallt? Header-Bar klingt sonst auch gut. Darf sich einfach nicht mit dem X in der Ecke beissen.

**Comment by swissspidy** [comment]
Drag & Drop gibt es nun nicht mehr. Fenster muss am Anfang / Ende nicht bewegt werden können und beim Highlighting ist eh nichts mehr im Weg (da Balken am unteren Bildschirmrand statt Fenster).
