### ISSUE TITLE
Support usage through other plugins

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#35]
Interesting suggestion/scenario by @webzunft:

As a developer, he'd like to support the User Feedback plugin in his own plugins.
1. He could tell plugin users to download User Feedback
2. They head to the plugin's options page and fill out the feedback form
3. The message is sent to the plugin author including additional debug information (e.g. all the plugin options)

Let's see what kind of hooks we need to support this.

After that we can document a sample integration in the wiki / readme

**Comment by neverything** [comment]
Great idea, would love to see this implemented as it would give others a chance to either write an add-on to support their custom bug tracking system and plugin others the possibilities you mentioned above.

**Comment by swissspidy** [comment]
As a plugin developer, declaring support for User Feedback should be as easy as possible. At the moment I prefer something like this:

```
do_action( 'user_feedback_init', array(
    'name'      => 'My Awesome Plugin',
    'data'      => array(), /* some additional debug data */
    'recipient' => 'example@example.com',
) );
```

This snippet would be placed on the page you want the feedback button to be shown, e.g. on an options page.

The question is how this implementation looks like in the User Feedback plugin.

Benefits:
- No `function_exists` check needed
- Options are passed as an array, so it's easily extensible in the future.

Downsides:
- Perhaps not that useful in every situation (?)
- Others?

Opinions?

**Comment by swissspidy** [comment]
Hooking into the `user_feedback_init` action:

```
public function user_feedback_init( $args ) {
    $defaults = array(
        'name'      => '',
        'data'      => array(),
        'recipient' => get_option( 'admin_email' ),
    );

    $args = wp_parse_args( $args, $defaults );

    add_filter( 'load_user_feedback', '__return_true' );

    add_filter( 'user_feedback_email_address', function () use ($args) {
        return $args['recipient'];
    } );

    add_filter( 'user_feedback_script_third_party_data', function () use ($args) {
        return array( sanitize_title( $args['name'] ) => $args['data'] );
    } );

    $this->enqueue_scripts();
}
```

**Comment by neverything** [comment]
I like the style and idea of this and prefer it over a `function_exists` call. Together with the `user_feedback_email_message` https://github.com/wearerequired/user-feedback/blob/master/user-feedback.php#L263 filter it's simple enough to add additional data to the email if necessary.

Trying to think about scenarios where this approach might have downsides, but can't come up with any at the moment, things like the following are already covered:
- Filter to add the additional data to the email
- Extensible array to add all kinds of arbitrary data for plugin devs
- Possible to overwrite the entire sending process to allow plugin devs to send the data somewhere else, for example an API.

So in my opinion it's a good way to continue.
