### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by sergejmueller** [wearerequired/user-feedback#37]
``` php
Parse error: syntax error, unexpected '[' in /www/htdocs/wp-content/plugins/user-feedback-master/user-feedback.php on line 136
```

:bomb: on PHP Version 5.3.28

**Comment by swissspidy** [comment]
💩

Thanks for the report! Can you confirm this on the `develop` branch too? This is the more up-to-date version of the plugin.

**Comment by sergejmueller** [comment]
The plugin version from `develop` branch works fine.

**Comment by swissspidy** [comment]
Puuh great :)
