### ISSUE TITLE
Chrome browser failed to dispaly the name and email address.

### ISSUE THREAD

**Issue by acherian7** [wearerequired/user-feedback#45]
Hi,

i installed user-feedback wp-plugin and it won't work to dispaly the name and email address on the chrome browser with new version.  Please let me know what i do the next step.  or update something.

Thanks,
Aju

**Comment by swissspidy** [comment]
Hey there

Thanks for your report. Are you logged in or not? These fields aren't displayed for logged-in users, because we already know who you are.

**Comment by acherian7** [comment]
Thanks, but I cleaned cookie or cache already still it failed.  What about public users to fill out the name and email address.

You know that I clicked on Take screenshot but it was slow to capture it then delayed to send.  Is there something wrong?

Thanks,
Aju

**Comment by acherian7** [comment]
http://www.test.interpretereducation.org/

**Comment by swissspidy** [comment]
> Thanks, but I cleaned cookie or cache already still it failed.  What about public users to fill out the name and email address.

I just visited your site and was able to add my name and email address. The data was properly saved and displayed in the later steps.

<img width="431" alt="screen shot 2015-10-28 at 17 47 03" src="https://cloud.githubusercontent.com/assets/841956/10795904/1d0dd20c-7d9c-11e5-99f6-c6d860fcee99.png">

> You know that I clicked on Take screenshot but it was slow to capture it then delayed to send.  Is there something wrong?

It's not uncommon for the screenshot option to take a while for large sites or sites that use lots of animations etc. Not much we can do about it unfortunately.

**Comment by acherian7** [comment]
Okay thank you for sharing.  I really like your user feedback plugins, but i do not want to confuse to any users.

**Comment by acherian7** [comment]
i tested on FireFox browsers, it looks good.   I will try to shut down my mac book and willl see what going on.  if it works using chrome browsers.

**Comment by acherian7** [comment]
BUT, when I try leave another message (see attach), the screenshot function is not working, see other screenshot.  Try for yourself.

**Comment by swissspidy** [comment]
> BUT, when I try leave another message (see attach), the screenshot function is not working, see other screenshot.  Try for yourself.

That's a known bug, see #38. I will close this issue in favour of that one.
