### ISSUE TITLE
Plugin breaks on upgrade to WP 4.4

### ISSUE THREAD

**Issue by brianrc** [wearerequired/user-feedback#52]
User Feedback 1.1.0

JavaScript console error:

```
http://mysite.xyz/wp-content/plugins/user-feedback/js/user-feedback.min%20.js?ver=1.0.0 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by swissspidy** [comment]
Thanks for your feedback!

It's not a caused by the update, but there was simply a space too much in our code. ed33aabf30e1515f46e501f4286b2302bfe14834 fixed this a couple of weeks ago.

We'll publish a new version soon!

**Comment by brianrc** [comment]
OK, but it actually did stop working after the update. Was working fine in WordPress 4.3.1  and broke immediately after upgrading. Looking forward to the new version. Thanks!
