### ISSUE TITLE
user_feedback_script_data filter doesn't exist

### ISSUE THREAD

**Issue by jakejackson1** [wearerequired/user-feedback#55]
In your docs you say the `user_feedback_script_data` filter can be used to modify the copy. I looked through the code for version 1.1.1 and found no mention on it.

The closest thing I found was the `user_feedback_support_data` filter but that doesn't seem to do anything useful.

**Comment by swissspidy** [comment]
Hey there,

Thanks for submitting this issue. It looks like I removed this by accident, as `Controller ::get_template_vars()` now isn't filterable any more.

**Comment by jakejackson1** [comment]
Glad to hear it's just an oversight. Your plugin looks fantastic (and well coded too) and I can't wait to give it a proper try. 

When do you think it will be added back in and pushed to WordPress.org?

**Comment by jakejackson1** [comment]
Just a follow up, when do you think the filter to change the copy will be added back in and pushed to WordPress.org?

**Comment by swissspidy** [comment]
@jakejackson1 We're now allocating some hours over the next week to update all our plugins on WordPress.org, including User Feedback.

This will most likely result in a revamped user flow (see #46).

Our testing with various users and clients showed that the process is too complicated and can be drastically simplified. Here's a demo of how it will look like: https://cloudup.com/c7ALm5HXwQS

Note that you'll still get a nice email with a screenshot when feedback is submitted. It's just hidden in the UI as it's not relevant for the user.

**Comment by jakejackson1** [comment]
That looks good! Can't wait to test it out.

**Comment by swissspidy** [comment]
Closing as this will be in 2.0.0.

Thanks again for reporting this.
