### ISSUE TITLE
change FROM email adress

### ISSUE THREAD

**Issue by codeagencybe** [wearerequired/user-feedback#59]
I'm using the option to send feedback directly to my support system (FreshDesk) from my visitors. 
I'm also collecting their e-mail address, but the emails sent are always from wordpress@mydomain.com

Can I change it somewhere so the FROM/sender ID = e-mail address that user fill in (or fetch from logged in user)?

Thanks!

BR,
Fabio

**Comment by swissspidy** [comment]
Hey there,

Thanks for opening this issue. `wordpress@mydomain.com` is the default address used by WordPress for all outgoing emails. There's currently not an easy way to change this for User Feedback emails only.

It definitely makes sense to change this as you described, but I'd also understand if someone would want to have something more generic like `feedback@mydomain.com` so they could filter their emails based on that.

Let me think about this a bit more to see if I can come up with a nice solution :-)

**Comment by codeagencybe** [comment]
Hi,

I made a small change myself as following by adding a snippet to my functions.php in child theme as following.
It will change the default outgoing FROM and EMAIL to anything I like to use but I can set it this way to my customer name and e-mail address. 
At least I will receive all incoming feedback from a correct e-mail address. 

I'm using FreshDesk with a dedicated mailbox "support@mydomain.com" and my client e-mail address is registered and approved to send it feedback and support tickets. 
So with below change, I'm 100% sure that all outgoing e-mails from the website will be an e-mail address that is registered in FreshDesk. 
And when I receive an e-mail this way, FreshDesk can identify my customer and sent back a ticket # to my customer. 

Perhaps you can use the below code to integrate in your plugin so the FROM and EMAIL can be dynamic depending on the name and email from user who is logged in? 

```
// Change default WordPress email address
add_filter('wp_mail_from', 'new_mail_from');
add_filter('wp_mail_from_name', 'new_mail_from_name');
function new_mail_from($email) {
return 'yourname@yourdomain.com';
}
function new_mail_from_name($name) {
return 'Your Name';
}

```
