### ISSUE TITLE
Summary Button

### ISSUE THREAD

**Issue by KarinChristen** [wearerequired/user-feedback#6]
Vorschlag für bessere Position und Darstellung

**Comment by swissspidy** [comment]
Gerade so nachgedacht: Wie wichtig ist die Beschriftung? Überall sonst wird "Next" verwendet. Evtl. kann man das hier ja einfach im gleichen Stil (rot auf weiss) nutzen?

**Comment by neverything** [comment]
To use the word "summary" there doesn't seem to trigger the mental model that this is the next step to take, unless it would be the only button available. We could play with the wording, maybe "next", "send", "view summary and send" or something the like would do the trick?

**Comment by swissspidy** [comment]
de oder en? :D

Jedenfalls +1 für "Send" oder "Send Feedback"

Wir haben ja noch erwähnt, dass der Highlight Modus nicht sehr offensichtlich ist. Wie wärs mit einer anderen Hintergrundfarbe für die Leiste unten? Etwa weiss oder auch blau. Wenn das nichts nützt wäre ein Hinweis (Pfeil, Pointer, etc.) der letzte Ausweg.

**Comment by KarinChristen** [comment]
Ich habe jetzt mal die Highlight Sache so visualisiert:
http://invis.io/TU2C0JHW4

Idee: Wir könnten ein cooles abstraktes gif malen um dem User noch zu zeigen was gemeint is oder so...

**Comment by swissspidy** [comment]
Der Flow ist mittlerweile komplett geändert und ich denke, das Problem mit dem Summary Button haben wir gelöst.
