### ISSUE TITLE
Anonyme User

### ISSUE THREAD

**Issue by KarinChristen** [wearerequired/user-feedback#7]
Vorschlag für Onboarding:
Name, e-Mail

**Comment by swissspidy** [comment]
@KarinChristen Werde das schon mal implementieren. Die Funktionalität braucht es ja sowieso, die Platzierung kann ich dann gemäss deinem Vorschlag anpassen.

**Comment by KarinChristen** [comment]
hier der Screen dazu:
http://invis.io/8Z2C0J39N
