### ISSUE TITLE
Screenshots uploaded to wrong directory

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/user-feedback#70]
As reported here: https://wordpress.org/support/topic/screenshot-store-in-wp-admin-folder/

Looks like due to using the wrong variable in the Ajax handler, the screenshot isn't stored in the tmp directory as intended, but instead inside wp-admin (because that's where `admin-ajax.php` resides).

**Comment by ocean90** [comment]
The AJAX handler is only using `wp_tempnam()` which returns a file **name**, not a path to a file name in a temporary directory.

https://github.com/wearerequired/user-feedback/blob/d29f02cf75156cc411852e44adefbf9791e45c3f/classes/AjaxHandler.php#L100

**Comment by swissspidy** [comment]
Based on my understanding, `wp_tempnam()` returns a file name with the path to the temp directory prepended: https://core.trac.wordpress.org/browser/tags/4.7/src/wp-admin/includes/file.php?marks=188#L188

The problem is the plugin renames that temp file and removes the path:

https://github.com/wearerequired/user-feedback/blob/d29f02cf75156cc411852e44adefbf9791e45c3f/classes/AjaxHandler.php#L107
