### ISSUE TITLE
is there a stable (compiled) release?

### ISSUE THREAD

**Issue by ManfredWisniewski** [wearerequired/user-feedback#73]
I currently do not have grunt installed on my work machine and running the project as-is does not work. Can you provide a compiled (grunt-ed) version of the plugin?

Thanks!

I am not sure whether this is grunt related: but none of the imports from /classes/ are working, I have had to manually add and include WP_Requirements_Check.php.
Even though I believe I have fixed most of the issues that grunt would do manually and I have no more explicit errors the feedback button is not displayed.

**Comment by swissspidy** [comment]
Hey there!

So there are two things in the plugin:

* Grunt, for doing some sanity checks and minifying JavaScript and CSS.
* Composer, for including external PHP dependencies like [WP Requirements Check](https://github.com/wearerequired/wp-requirements-check).

The actual built plugin you're looking for can be found [on WordPress.org](https://wordpress.org/plugins/user-feedback/). Currently, you can download version 1.x there. For version 2 (alpha / beta), click on [Advanced View](https://wordpress.org/plugins/user-feedback/advanced/) and select _Development Version_ at the bottom.

**Comment by ManfredWisniewski** [comment]
Thank you very much! Version 1 works fine for me currently. If I run into any issues I will take some more time and have a look at the development version.
