### ISSUE TITLE
Mobile: Modal out of view and click on bubble doesn't restore modal anymore

### ISSUE THREAD

**Issue by ocean90** [wearerequired/user-feedback#82]
<img width="375" alt="ios" src="https://user-images.githubusercontent.com/617637/29895226-988ccdfe-8dd8-11e7-8ba6-206f6998bca8.png">

This was also mentioned in https://wordpress.org/support/topic/missing-responsive-styling/ (and #71 but with a different focus)

**Todo**

- [x] Modal out of view
- [ ] Click on bubble doesn't restore modal

**Comment by ocean90** [comment]
@KarinChristen @velthy Do you have any ideas how we could make the modal look nice/useful on mobile?

**Comment by velthy** [comment]
On small screens (or generally if there is not enough space to the right or left), we should center the modal window:
![feedback-overlay-small-screens](https://user-images.githubusercontent.com/3276054/33204724-b50be4f0-d104-11e7-8b69-3c6173cc1e71.png)

As for the vertical alignment: If the selected area is in the middle of the screen, or there is not enough space to the top, the modal should be displayed underneath the blue bubble. In that case, the (whole) screen should be scrollable.

Feedback/Questions?

**Comment by ocean90** [comment]
Clicking on the button still doesn't work correctly. The `hidden` class doesn't get removed.
