### ISSUE TITLE
Change the From email address to user email address

### ISSUE THREAD

**Issue by alvarogois** [wearerequired/user-feedback#91]
I’m trying to make User Feedback work with a support ticket solution, for example [Catchers](https://wordpress.org/plugins/catchers-helpdesk/). It would make it possible to log and reply to feedback inside WordPress. Catchers also lets you have an external email flow that the plugin can fetch and log inside WordPress, making it useful for logging issues and having several different agents responding to issues.

I have a problem with this flow though. I need the `From` email address to be the users’ and not the site’s email address, so that one can make a direct reply to the email, not having to edit the `To` name and address.

How can I change the `From` email address to be the user’s email address?

(I have opened a [support topic on WordPress.org](https://wordpress.org/support/topic/change-the-from-email-address-to-user-email-address/) also)

**Comment by swissspidy** [comment]
Hey Alvaro,

Thanks for reaching out! We've changed the behaviour to set the user's email address as the `From` email in #59 / 54c628998f3ebdea334487654b6535bd67eb83ff. This change is only available in version 2.0 though, which is currently in beta. To use that version, visit https://wordpress.org/plugins/user-feedback/advanced/ and select "Development Version" at the bottom.

**Note:** Version 2.0 has quite a different user flow, so don't be surprised. It isn't 100% set in stone yet, so if you have any feedback on that version, please let us know here. That would be greatly appreciated!

If you want to stick with version 1.1.1 for now, I can try looking into how to change the `From` email address for that version.

----

With that being said, would you be interested in having a direct integration with Catchers? Meaning that submitting the feedback form would directly create a new entry in the ticket system without sending any email.

**Comment by alvarogois** [comment]
Hi Pascal,

Thank you for your reply. And thank you for sharing this awesome tool. It looks simple and very useful indeed.

I'm testing the 2.0.0-beta.4 version. I was not aware this was already being dealt with in #59. 

I guess my issue is similar to @codeagencybe. But I'm not getting it to work. I use a specific email address (like feedback@mydomain) so that Catchers can fetch the emails and add it to it's own flow. But when Catchers grabs the email, the sender address is not the user's but the website address, therefore, the flow is not working.

Direct integration with Catchers would be perfect! I tried Catchers because it's available in WP.org and I think the flow is quite efficient.

Would it be hard to integrate both plugins that way? I'm not a dev so I have no idea how this can be achieved.

Thanks.

**Comment by alvarogois** [comment]
I've not tested the 1.1.1 version, hence I cannot assess the user flow changes in version 2.0.

I like the way it works in 2.0.0-beta.4. I tested specifically for logged-in users, to collect their feedback on specific pages.

**Comment by swissspidy** [comment]
Just so I understand it right, the `From` email address is still not correct in 2.0.0-beta.4?

Regarding the Catchers integration: I'd have to have a closer look at it, but as long as the plugin doesn't do some very unusual things in WordPress it's certainly possible and wouldn't take too much time. However, we need to lay the proper groundwork for extensions like this first.

**Comment by alvarogois** [comment]
Hi @swissspidy, sorry for the delay. I figured out why the <code>From</code> email was not being sent correctly. I was testing locally with an SMTP plugin enabled. The email was being sent with the site email address, not the user email. With the SMTP plugin disabled, the email is received with the user's address. Thanks!

As to the integration, I understand what you mean. In the meantime, I'll figure a way to make it work using the email fetch function of Catchers. That was my primary concern, after all.
